### ISSUE TITLE
Game hangs on exit

### ISSUE THREAD

**Issue by benjamincongdon** [gragas/adept#64]
In the latest version of `develop` the game hangs on exiting fairly frequently. I think Tom said this was due to the multiprocessing stuff.

This is a fairly critical bug, as occasionally on Mac this makes the whole system unresponsive.

**Comment by gragas** [comment]
Yes, this is really annoying. I'm trying to move everything over to threading instead of multiprocessing so this sort of thing can't happen.

**Comment by benjamincongdon** [comment]
With some very unscientific testing, it seems like this mostly occurs when you quit while the multiprocessing loading is going on.

**Comment by gragas** [comment]
Yeah, exactly. What happens is, if the main process exits when its child processes are still running, they don't close like they're supposed to. I've set the `daemon` flag for each process, but according to official Python documentation, the daemon flag is not guaranteed to exit all child process on every system. It seems that this is this case for UNIX-based systems especially. I'm probably just doing something wrong, but to fix the issue I'm going to try to switch to the `threading` module instead of doing daemon process hackery.

**Comment by gragas** [comment]
#66 closes this issue
