### ISSUE TITLE
Coordinate system

### ISSUE THREAD

**Issue by benjamincongdon** [gragas/adept#8]
How should we track the coordinates in the world?
In terms of tiles, chunks, pixels, etc?

Regardless, we'll need to think of a way to convert between coords and the x,y grid of chunks for loading chunks at a given position.

**Comment by gragas** [comment]
I think we need to establish three positions, and be able to translate between them:

   1. Global position
   2. Position relative to the camera
   3. Position relative to the surrounding chunk

All of these should be measured in pixels.

The camera's position can really be thought of as a vector which translates objects to some position.

For example, suppose there is a chest at the global position (500, 500), and the player is at the global position (400, 400). (Since the camera is locked to the player, its position is (400, 400), as well.) When actually rendering the chest, we'd simply take the chest's global position and element-wise subtract the camera's global position. So the chest would be rendered at (100, 100) on the screen, about 141 pixels away from the character, as intended.
